name: build-stable

on:
  workflow_dispatch:
    inputs:
      operating-system:
        description: <ios|android>
        required: true

jobs:
  build-stable:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          # Build the stable branch.
          # https://github.com/actions/checkout#usage
          ref: stable

      - name: Set up Node.js v12
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Set up Expo CLI
        uses: expo/expo-github-action@v5
        with:
          expo-version: 4.x
          expo-token: ${{ secrets.EXPO_ACCESS_TOKEN }}

      # Cache the node_modules directory
      - name: Set up node_modules cache
        uses: actions/cache@v2
        id: node-modules-cache
        with:
          key: node-modules-cache-${{ hashFiles('**/yarn.lock') }}
          path: '**/node_modules'

      - name: Install dependencies
        if: steps.node-modules-cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile

      - name: Build the application
        run: sh ./scripts/build.sh ${{ github.event.inputs.operating-system }}
